package com.ahmetgezici.covid19app.Class;

import com.ahmetgezici.covid19app.R;

import java.util.HashMap;

public class CountryAndFlag {

    private static HashMap<String, Integer> flagHashMap;
    private static HashMap<String, String> countryHashMap;

    public CountryAndFlag() {
        flagSet();
        countrySet();
    }

    public static int flagSearch(String flagName) {
        if (flagHashMap.get(flagName) != null) {
            return flagHashMap.get(flagName);
        }
        return R.drawable.ic_flag;
    }

    public static String countrySearch(String countryName) {
        if (countryHashMap.get(countryName) != null) {
            return countryHashMap.get(countryName);
        }
        return countryName;
    }

    private static void flagSet() {
        flagHashMap = new HashMap<>();
        flagHashMap.put("ABD", R.drawable.united_states_of_america);
        flagHashMap.put("İspanya", R.drawable.spain);
        flagHashMap.put("İtalya", R.drawable.italy);
        flagHashMap.put("Almanya", R.drawable.germany);
        flagHashMap.put("Fransa", R.drawable.france);
        flagHashMap.put("Çin", R.drawable.china);
        flagHashMap.put("İran", R.drawable.iran);
        flagHashMap.put("İngiltere", R.drawable.united_kingdom);
        flagHashMap.put("Türkiye", R.drawable.turkey);
        flagHashMap.put("Belçika", R.drawable.belgium);
        flagHashMap.put("İsviçre", R.drawable.switzerland);
        flagHashMap.put("Hollanda", R.drawable.netherlands);
        flagHashMap.put("Kanada", R.drawable.canada);
        flagHashMap.put("Brezilya", R.drawable.brazil);
        flagHashMap.put("Portekiz", R.drawable.portugal);
        flagHashMap.put("Avusturya", R.drawable.austria);
        flagHashMap.put("Güney Kore", R.drawable.south_korea);
        flagHashMap.put("İsrail", R.drawable.israel);
        flagHashMap.put("Rusya", R.drawable.russia);
        flagHashMap.put("İsveç", R.drawable.sweden);
        flagHashMap.put("Norveç", R.drawable.norway);
        flagHashMap.put("Avustralya", R.drawable.australia);
        flagHashMap.put("İrlanda", R.drawable.ireland);
        flagHashMap.put("Hindistan", R.drawable.india);
        flagHashMap.put("Şili", R.drawable.chile);
        flagHashMap.put("Danimarka", R.drawable.denmark);
        flagHashMap.put("Çekya", R.drawable.czech_republic);
        flagHashMap.put("Polonya", R.drawable.republic_of_poland);
        flagHashMap.put("Romanya", R.drawable.romania);
        flagHashMap.put("Japonya", R.drawable.japan);
        flagHashMap.put("Pakistan", R.drawable.pakistan);
        flagHashMap.put("Ekvador", R.drawable.ecuador);
        flagHashMap.put("Malezya", R.drawable.malaysia);
        flagHashMap.put("Filipinler", R.drawable.philippines);
        flagHashMap.put("Lüksemburg", R.drawable.luxembourg);
        flagHashMap.put("Peru", R.drawable.peru);
        flagHashMap.put("Suudi Arabistan", R.drawable.saudi_arabia);
        flagHashMap.put("Meksika", R.drawable.mexico);
        flagHashMap.put("Endonezya", R.drawable.indonesia);
        flagHashMap.put("Sırbistan", R.drawable.serbia);
        flagHashMap.put("Tayland", R.drawable.thailand);
        flagHashMap.put("Birleşik Arap Emirlikleri", R.drawable.united_arab_emirates);
        flagHashMap.put("Finlandiya", R.drawable.finland);
        flagHashMap.put("Panama", R.drawable.panama);
        flagHashMap.put("Katar", R.drawable.qatar);
        flagHashMap.put("Dominik Cumhuriyeti", R.drawable.dominican_republic);
        flagHashMap.put("Yunanistan", R.drawable.greece);
        flagHashMap.put("Kolombiya", R.drawable.colombia);
        flagHashMap.put("Güney Afrika", R.drawable.south_africa);
        flagHashMap.put("Arjantin", R.drawable.argentina);
        flagHashMap.put("Ukrayna", R.drawable.ukraine);
        flagHashMap.put("İzlanda", R.drawable.iceland);
        flagHashMap.put("Singapur", R.drawable.singapore);
        flagHashMap.put("Cezayir", R.drawable.algeria);
        flagHashMap.put("Mısır", R.drawable.egypt);
        flagHashMap.put("Hırvatistan", R.drawable.croatia);
        flagHashMap.put("Yeni Zelanda", R.drawable.new_zealand);
        flagHashMap.put("Fas", R.drawable.morocco);
        flagHashMap.put("Estonya", R.drawable.estonia);
        flagHashMap.put("Irak", R.drawable.iraq);
        flagHashMap.put("Slovenya", R.drawable.slovenia);
        flagHashMap.put("Moldova", R.drawable.moldova);
        flagHashMap.put("Hong Kong", R.drawable.hong_kong);
        flagHashMap.put("Litvanya", R.drawable.lithuania);
        flagHashMap.put("Macaristan", R.drawable.hungary);
        flagHashMap.put("Beyaz Rusya", R.drawable.belarus);
        flagHashMap.put("Ermenistan", R.drawable.armenia);
        flagHashMap.put("Bahreyn", R.drawable.bahrain);
        flagHashMap.put("Bosna-Hersek", R.drawable.bosnia_and_herzegovina);
        flagHashMap.put("Kuveyt", R.drawable.kuwait);
        flagHashMap.put("Azerbaycan", R.drawable.azerbaijan);
        flagHashMap.put("Kazakistan", R.drawable.kazakhstan);
        flagHashMap.put("Diamond Princess", R.drawable.cruise);
        flagHashMap.put("Kamerun", R.drawable.cameroon);
        flagHashMap.put("Tunus", R.drawable.tunisia);
        flagHashMap.put("Kuzey Makedonya", R.drawable.republic_of_macedonia);
        flagHashMap.put("Bulgaristan", R.drawable.bulgaria);
        flagHashMap.put("Slovakya", R.drawable.slovakia);
        flagHashMap.put("Lübnan", R.drawable.lebanon);
        flagHashMap.put("Letonya", R.drawable.latvia);
        flagHashMap.put("Andorra", R.drawable.andorra);
        flagHashMap.put("Özbekistan", R.drawable.uzbekistn);
        flagHashMap.put("Güney Kıbrıs", R.drawable.cyprus);
        flagHashMap.put("Kosta Rika", R.drawable.costa_rica);
        flagHashMap.put("Uruguay", R.drawable.uruguay);
        flagHashMap.put("Afganistan", R.drawable.afghanistan);
        flagHashMap.put("Umman", R.drawable.oman);
        flagHashMap.put("Küba", R.drawable.cuba);
        flagHashMap.put("Burkina Faso", R.drawable.burkina_faso);
        flagHashMap.put("Arnavutluk", R.drawable.albania);
        flagHashMap.put("Tayvan", R.drawable.taiwan);
        flagHashMap.put("Réunion", R.drawable.france);
        flagHashMap.put("Ürdün", R.drawable.jordan);
        flagHashMap.put("Fildişi Sahili", R.drawable.ivory_coast);
        flagHashMap.put("Manş Adaları", R.drawable.england);
        flagHashMap.put("Honduras", R.drawable.honduras);
        flagHashMap.put("Malta", R.drawable.malta);
        flagHashMap.put("Gana", R.drawable.ghana);
        flagHashMap.put("San Marino", R.drawable.san_marino);
        flagHashMap.put("Nijer", R.drawable.niger);
        flagHashMap.put("Kırgızistan", R.drawable.kyrgyzstan);
        flagHashMap.put("Mauritius", R.drawable.mauritius);
        flagHashMap.put("Filistin", R.drawable.palestine);
        flagHashMap.put("Nijerya", R.drawable.nigeria);
        flagHashMap.put("Vietnam", R.drawable.vietnam);
        flagHashMap.put("Karadağ", R.drawable.montenegro);
        flagHashMap.put("Senegal", R.drawable.senegal);
        flagHashMap.put("Bolivya", R.drawable.bolivia);
        flagHashMap.put("Gürcistan", R.drawable.georgia);
        flagHashMap.put("Kosova", R.drawable.kosovo);
        flagHashMap.put("Faroe Adaları", R.drawable.faroe_islands);
        flagHashMap.put("Kongo DC", R.drawable.democratic_republic_of_congo);
        flagHashMap.put("Kenya", R.drawable.kenya);
        flagHashMap.put("Mayotte", R.drawable.france);
        flagHashMap.put("Venezuela", R.drawable.venezuela);
        flagHashMap.put("Bangladeş", R.drawable.bangladesh);
        flagHashMap.put("Martinik", R.drawable.martinique);
        flagHashMap.put("Man Adası", R.drawable.isle_of_man);
        flagHashMap.put("Gine", R.drawable.guinea);
        flagHashMap.put("Guadeloupe", R.drawable.france);
        flagHashMap.put("Sri Lanka", R.drawable.sri_lanka);
        flagHashMap.put("Brunei", R.drawable.brunei);
        flagHashMap.put("Paraguay", R.drawable.paraguay);
        flagHashMap.put("Kamboçya", R.drawable.cambodia);
        flagHashMap.put("Cebelitarık", R.drawable.gibraltar);
        flagHashMap.put("Trinidad ve Tobago", R.drawable.trinidad_and_tobago);
        flagHashMap.put("Ruanda", R.drawable.rwanda);
        flagHashMap.put("KKTC", R.drawable.northen_cyprus);
        flagHashMap.put("Lihtenştayn", R.drawable.liechtenstein);
        flagHashMap.put("Madagaskar", R.drawable.madagascar);
        flagHashMap.put("Monako", R.drawable.monaco);
        flagHashMap.put("Aruba", R.drawable.aruba);
        flagHashMap.put("Fransız Guyanası", R.drawable.france);
        flagHashMap.put("El Salvador", R.drawable.salvador);
        flagHashMap.put("Jamaika", R.drawable.jamaica);
        flagHashMap.put("Barbados", R.drawable.barbados);
        flagHashMap.put("Guatemala", R.drawable.guatemala);
        flagHashMap.put("Cibuti", R.drawable.djibouti);
        flagHashMap.put("Uganda", R.drawable.uganda);
        flagHashMap.put("Makao", R.drawable.macao);
        flagHashMap.put("Togo", R.drawable.togo);
        flagHashMap.put("Mali", R.drawable.mali);
        flagHashMap.put("Zambiya", R.drawable.zambia);
        flagHashMap.put("Fransız Polinezyası", R.drawable.french_polynesia);
        flagHashMap.put("Etiyopya", R.drawable.ethiopia);
        flagHashMap.put("Bermuda", R.drawable.bermuda);
        flagHashMap.put("Cayman Adaları", R.drawable.cayman_islands);
        flagHashMap.put("Saint Martin", R.drawable.france);
        flagHashMap.put("Bahamalar", R.drawable.bahamas);
        flagHashMap.put("Guyana", R.drawable.guyana);
        flagHashMap.put("Sint Maarten", R.drawable.sint_maarten);
        flagHashMap.put("Kongo Cumhuriyeti", R.drawable.republic_of_the_congo);
        flagHashMap.put("Eritre", R.drawable.eritrea);
        flagHashMap.put("Gabon", R.drawable.gabon);
        flagHashMap.put("Burma (Myanmar)", R.drawable.myanmar);
        flagHashMap.put("Tanzanya", R.drawable.tanzania);
        flagHashMap.put("Maldivler", R.drawable.maldives);
        flagHashMap.put("Yeni Kaledonya", R.drawable.france);
        flagHashMap.put("Haiti", R.drawable.haiti);
        flagHashMap.put("Libya", R.drawable.libya);
        flagHashMap.put("Suriye", R.drawable.syria);
        flagHashMap.put("Ekvator Ginesi", R.drawable.equatorial_guinea);
        flagHashMap.put("Benin", R.drawable.benin);
        flagHashMap.put("Gine-Bissau", R.drawable.guinea_bissau);
        flagHashMap.put("Antigua ve Barbuda", R.drawable.antigua_and_barbuda);
        flagHashMap.put("Dominika", R.drawable.dominica);
        flagHashMap.put("Namibya", R.drawable.namibia);
        flagHashMap.put("Moğolistan", R.drawable.mongolia);
        flagHashMap.put("Saint Lucia", R.drawable.st_lucia);
        flagHashMap.put("Fiji", R.drawable.fiji);
        flagHashMap.put("Grenada", R.drawable.grenada);
        flagHashMap.put("Curaçao", R.drawable.curacao);
        flagHashMap.put("Grönland", R.drawable.greenland);
        flagHashMap.put("Seyşeller", R.drawable.seychelles);
        flagHashMap.put("Laos", R.drawable.laos);
        flagHashMap.put("Surinam", R.drawable.suriname);
        flagHashMap.put("Mozambik", R.drawable.mozambique);
        flagHashMap.put("Sudan", R.drawable.sudan);
        flagHashMap.put("Liberya", R.drawable.liberia);
        flagHashMap.put("MS Zaandam", R.drawable.cruise);
        flagHashMap.put("Zimbabve", R.drawable.zimbabwe);
        flagHashMap.put("Çad", R.drawable.chad);
        flagHashMap.put("Saint Kitts ve Nevis", R.drawable.saint_kitts_and_nevis);
        flagHashMap.put("Nepal", R.drawable.nepal);
        flagHashMap.put("Angola", R.drawable.angola);
        flagHashMap.put("Orta Afrika Cumhuriyeti", R.drawable.central_african_republic);
        flagHashMap.put("Yeşil Burun Adaları", R.drawable.cape_verde);
        flagHashMap.put("Somali", R.drawable.somalia);
        flagHashMap.put("Saint Vincent ve Grenadinler", R.drawable.st_vincent_and_the_grenadines);
        flagHashMap.put("Vatikan", R.drawable.vatican_city);
        flagHashMap.put("Moritanya", R.drawable.mauritania);
        flagHashMap.put("Saint Barthélemy", R.drawable.france);
        flagHashMap.put("Porto Riko", R.drawable.puerto_rico);
        flagHashMap.put("USS Theodore Roosevelt", R.drawable.cruise);
        flagHashMap.put("Guernsey", R.drawable.guernsey);
        flagHashMap.put("Jersey", R.drawable.jersey);
        flagHashMap.put("Guam", R.drawable.guam);
        flagHashMap.put("Greg Mortimer", R.drawable.cruise);
        flagHashMap.put("Sierra Leone", R.drawable.sierra_leone);
        flagHashMap.put("Esvati̇ni̇", R.drawable.swaziland);
        flagHashMap.put("ABD Virjin Adaları", R.drawable.virgin_islands);
        flagHashMap.put("Britanya Virjin Adaları", R.drawable.british_virgin_islands);
        flagHashMap.put("Donetsk Halk Cumhuriyeti", R.drawable.ukraine);
        flagHashMap.put("Luhansk Halk Cumhuriyeti", R.drawable.ukraine);
        flagHashMap.put("Malavi", R.drawable.malawi);
        flagHashMap.put("Güney Sudan", R.drawable.south_sudan);
        flagHashMap.put("Doğu Timor", R.drawable.east_timor);
        flagHashMap.put("Botsvana", R.drawable.botswana);
        flagHashMap.put("Belize", R.drawable.belize);
        flagHashMap.put("Kuzey Mariana Adaları", R.drawable.northern_marianas_islands);
        flagHashMap.put("Ağrotur ve Dikelya", R.drawable.united_kingdom);
        flagHashMap.put("Åland Adaları", R.drawable.aland_islands);
        flagHashMap.put("Montserrat", R.drawable.montserrat);
        flagHashMap.put("Turks ve Caicos Adaları", R.drawable.turks_and_caicos);
        flagHashMap.put("Nikaragua", R.drawable.nicaragua);
        flagHashMap.put("Butan", R.drawable.bhutan_1);
        flagHashMap.put("Falkland Adaları", R.drawable.falkland_islands);
        flagHashMap.put("Gambiya", R.drawable.gambia);
        flagHashMap.put("São Tomé and Príncipe", R.drawable.sao_tome_and_principe);
        flagHashMap.put("Anguilla", R.drawable.anguilla);
        flagHashMap.put("Burundi", R.drawable.burundi);
        flagHashMap.put("Papua Yeni Gine", R.drawable.papua_new_guinea);
        flagHashMap.put("Sint Eustatius", R.drawable.sint_eustatius);
        flagHashMap.put("Somaliland", R.drawable.somaliland);
        flagHashMap.put("Abhazya", R.drawable.abkhazia);
        flagHashMap.put("Artsah Cumhuriyeti", R.drawable.armenia);
        flagHashMap.put("Guantanamo Kampı", R.drawable.cuba);
        flagHashMap.put("Yemen", R.drawable.yemen);
        flagHashMap.put("Coral Princess", R.drawable.cruise);
        flagHashMap.put("Saint Pierre ve Miquelon", R.drawable.france);
        flagHashMap.put("Saba Adası", R.drawable.saba_island);
        flagHashMap.put("Bonaire", R.drawable.bonaire);
        flagHashMap.put("HNLMS Dolfijn", R.drawable.cruise);
        flagHashMap.put("Charles de Gaulle", R.drawable.cruise);
        flagHashMap.put("Costa Atlantica", R.drawable.cruise);
        flagHashMap.put("USS Kidd", R.drawable.cruise);
        flagHashMap.put("Komorlar", R.drawable.comoros);
        flagHashMap.put("Tacikistan", R.drawable.tajikistan);
        flagHashMap.put("Lesotho", R.drawable.lesotho);
        flagHashMap.put("Güney Osetya", R.drawable.ossetia);
        flagHashMap.put("Solomon Adaları", R.drawable.solomon_islands);
        flagHashMap.put("Wallis ve Futuna", R.drawable.france);
        flagHashMap.put("Sahra Dem. Arap Cum.", R.drawable.western_sahara);
        flagHashMap.put("Marshall Adaları", R.drawable.marshall_island);
        flagHashMap.put("Vanuatu", R.drawable.vanuatu);
        flagHashMap.put("Samoa", R.drawable.samoa);
        flagHashMap.put("Amerikan Samoası", R.drawable.american_samoa);
        flagHashMap.put("SeaDream I", R.drawable.cruise);

    }

    private static void countrySet() {
        countryHashMap = new HashMap<>();
        countryHashMap.put("United States", "ABD");
        countryHashMap.put("Spain", "İspanya");
        countryHashMap.put("Italy", "İtalya");
        countryHashMap.put("Germany", "Almanya");
        countryHashMap.put("France", "Fransa");
        countryHashMap.put("China", "Çin");
        countryHashMap.put("China (mainland)", "Çin");
        countryHashMap.put("Iran", "İran");
        countryHashMap.put("United Kingdom", "İngiltere");
        countryHashMap.put("Turkey", "Türkiye");
        countryHashMap.put("Belgium", "Belçika");
        countryHashMap.put("Switzerland", "İsviçre");
        countryHashMap.put("Netherlands", "Hollanda");
        countryHashMap.put("Canada", "Kanada");
        countryHashMap.put("Brazil", "Brezilya");
        countryHashMap.put("Portugal", "Portekiz");
        countryHashMap.put("Austria", "Avusturya");
        countryHashMap.put("South Korea", "Güney Kore");
        countryHashMap.put("Israel", "İsrail");
        countryHashMap.put("Russia", "Rusya");
        countryHashMap.put("Sweden", "İsveç");
        countryHashMap.put("Norway", "Norveç");
        countryHashMap.put("Australia", "Avustralya");
        countryHashMap.put("Ireland", "İrlanda");
        countryHashMap.put("India", "Hindistan");
        countryHashMap.put("Chile", "Şili");
        countryHashMap.put("Denmark", "Danimarka");
        countryHashMap.put("Czech Republic", "Çekya");
        countryHashMap.put("Poland", "Polonya");
        countryHashMap.put("Romania", "Romanya");
        countryHashMap.put("Japan", "Japonya");
        countryHashMap.put("Ecuador", "Ekvador");
        countryHashMap.put("Malaysia", "Malezya");
        countryHashMap.put("Philippines", "Filipinler");
        countryHashMap.put("Luxembourg", "Lüksemburg");
        countryHashMap.put("Saudi Arabia", "Suudi Arabistan");
        countryHashMap.put("Mexico", "Meksika");
        countryHashMap.put("Indonesia", "Endonezya");
        countryHashMap.put("Serbia", "Sırbistan");
        countryHashMap.put("Thailand", "Tayland");
        countryHashMap.put("United Arab Emirates", "Birleşik Arap Emirlikleri");
        countryHashMap.put("Finland", "Finlandiya");
        countryHashMap.put("Qatar", "Katar");
        countryHashMap.put("Dominican Republic", "Dominik Cumhuriyeti");
        countryHashMap.put("Greece", "Yunanistan");
        countryHashMap.put("Colombia", "Kolombiya");
        countryHashMap.put("South Africa", "Güney Afrika");
        countryHashMap.put("Argentina", "Arjantin");
        countryHashMap.put("Ukraine", "Ukrayna");
        countryHashMap.put("Iceland", "İzlanda");
        countryHashMap.put("Singapore", "Singapur");
        countryHashMap.put("Algeria", "Cezayir");
        countryHashMap.put("Egypt", "Mısır");
        countryHashMap.put("Croatia", "Hırvatistan");
        countryHashMap.put("New Zealand", "Yeni Zelanda");
        countryHashMap.put("Morocco", "Fas");
        countryHashMap.put("Estonia", "Estonya");
        countryHashMap.put("Iraq", "Irak");
        countryHashMap.put("Slovenia", "Slovenya");
        countryHashMap.put("Hong Kong", "Hong Kong");
        countryHashMap.put("Lithuania", "Litvanya");
        countryHashMap.put("Hungary", "Macaristan");
        countryHashMap.put("Belarus", "Beyaz Rusya");
        countryHashMap.put("Armenia", "Ermenistan");
        countryHashMap.put("Bahrain", "Bahreyn");
        countryHashMap.put("Bosnia and Herzegovina", "Bosna-Hersek");
        countryHashMap.put("Bosnia & Herzegovina", "Bosna-Hersek");
        countryHashMap.put("Kuwait", "Kuveyt");
        countryHashMap.put("Azerbaijan", "Azerbaycan");
        countryHashMap.put("Kazakhstan", "Kazakistan");
        countryHashMap.put("Cameroon", "Kamerun");
        countryHashMap.put("Slovakia", "Slovakya");
        countryHashMap.put("Puerto Rico", "Porto Riko");
        countryHashMap.put("North Macedonia", "Kuzey Makedonya");
        countryHashMap.put("Tunisia", "Tunus");
        countryHashMap.put("Bulgaria", "Bulgaristan");
        countryHashMap.put("Latvia", "Letonya");
        countryHashMap.put("Lebanon", "Lübnan");
        countryHashMap.put("Uzbekistan", "Özbekistan");
        countryHashMap.put("Cyprus", "Güney Kıbrıs");
        countryHashMap.put("Costa Rica", "Kosta Rika");
        countryHashMap.put("Afghanistan", "Afganistan");
        countryHashMap.put("Oman", "Umman");
        countryHashMap.put("Albania", "Arnavutluk");
        countryHashMap.put("Ivory Coast", "Fildişi Sahili");
        countryHashMap.put("Taiwan", "Tayvan");
        countryHashMap.put("Jordan", "Ürdün");
        countryHashMap.put("Niger", "Nijer");
        countryHashMap.put("Bangladesh", "Bangladeş");
        countryHashMap.put("Ghana", "Gana");
        countryHashMap.put("Kyrgyzstan", "Kırgızistan");
        countryHashMap.put("Nigeria", "Nijerya");
        countryHashMap.put("Bolivia", "Bolivya");
        countryHashMap.put("Palestine", "Filistin");
        countryHashMap.put("Montenegro", "Karadağ");
        countryHashMap.put("Kosovo", "Kosova");
        countryHashMap.put("Georgia", "Gürcistan");
        countryHashMap.put("Faroe Islands", "Faroe Adaları");
        countryHashMap.put("DR Congo", "Kongo DC");
        countryHashMap.put("Isle of Man", "Man Adası");
        countryHashMap.put("Guinea", "Gine");
        countryHashMap.put("Martinique", "Martinik");
        countryHashMap.put("Djibouti", "Cibuti");
        countryHashMap.put("Cuba", "Küba");
        countryHashMap.put("Gibraltar", "Cebelitarık");
        countryHashMap.put("Cambodia", "Kamboçya");
        countryHashMap.put("Rwanda", "Ruanda");
        countryHashMap.put("Trinidad and Tobago", "Trinidad ve Tobago");
        countryHashMap.put("Northern Cyprus", "KKTC");
        countryHashMap.put("Madagascar", "Madagaskar");
        countryHashMap.put("French Guiana", "Fransız Guyanası");
        countryHashMap.put("Monaco", "Monako");
        countryHashMap.put("Liechtenstein", "Lihtenştayn");
        countryHashMap.put("Jamaica", "Jamaika");
        countryHashMap.put("Ethiopia", "Etiyopya");
        countryHashMap.put("French Polynesia", "Fransız Polinezyası");
        countryHashMap.put("Cayman Islands", "Cayman Adaları");
        countryHashMap.put("Republic of the Congo", "Kongo Cumhuriyeti");
        countryHashMap.put("Congo", "Kongo Cumhuriyeti");
        countryHashMap.put("Macau", "Makao");
        countryHashMap.put("U.S. Virgin Islands", "ABD Virjin Adaları");
        countryHashMap.put("Bahamas", "Bahamalar");
        countryHashMap.put("Zambia", "Zambiya");
        countryHashMap.put("Eritrea", "Eritre");
        countryHashMap.put("Guinea-Bissau", "Gine-Bissau");
        countryHashMap.put("Liberia", "Liberya");
        countryHashMap.put("Tanzania", "Tanzanya");
        countryHashMap.put("Myanmar", "Burma (Myanmar)");
        countryHashMap.put("Antigua and Barbuda", "Antigua ve Barbuda");
        countryHashMap.put("Maldives", "Maldivler");
        countryHashMap.put("Syria", "Suriye");
        countryHashMap.put("Equatorial Guinea", "Ekvator Ginesi");
        countryHashMap.put("New Caledonia", "Yeni Kaledonya");
        countryHashMap.put("Mozambique", "Mozambik");
        countryHashMap.put("Mongolia", "Moğolistan");
        countryHashMap.put("Namibia", "Namibya");
        countryHashMap.put("Dominica", "Dominika");
        countryHashMap.put("Botswana", "Botsvana");
        countryHashMap.put("Eswatini", "Esvati̇ni̇");
        countryHashMap.put("Grenada", "Grenada");
        countryHashMap.put("Somalia", "Somali");
        countryHashMap.put("MS Zaandam & Rotterdam", "MS Zaandam");
        countryHashMap.put("Zimbabwe", "Zimbabve");
        countryHashMap.put("Saint Kitts and Nevis", "Saint Kitts ve Nevis");
        countryHashMap.put("Seychelles", "Seyşeller");
        countryHashMap.put("Greenland", "Grönland");
        countryHashMap.put("Northern Mariana Islands ", "Kuzey Mariana Adaları");
        countryHashMap.put("Suriname", "Surinam");
        countryHashMap.put("Akrotiri and Dhekelia", "Ağrotur ve Dikelya");
        countryHashMap.put("Chad", "Çad");
        countryHashMap.put("Åland Islands", "Åland Adaları");
        countryHashMap.put("Central African Republic", "Orta Afrika Cumhuriyeti");
        countryHashMap.put("Malawi", "Malavi");
        countryHashMap.put("Montserrat", "Montserrat");
        countryHashMap.put("Saint Vincent", "Saint Vincent ve Grenadinler");
        countryHashMap.put("Saint Vincent and The Grenadines", "Saint Vincent ve Grenadinler");
        countryHashMap.put("Turks and Caicos Islands", "Turks ve Caicos Adaları");
        countryHashMap.put("Vatican City", "Vatikan");
        countryHashMap.put("Cape Verde", "Yeşil Burun Adaları");
        countryHashMap.put("Mauritania", "Moritanya");
        countryHashMap.put("Nicaragua", "Nikaragua");
        countryHashMap.put("Saint Barthélemy", "Saint Barthélemy");
        countryHashMap.put("Donetsk PR", "Donetsk Halk Cumhuriyeti");
        countryHashMap.put("Bhutan", "Butan");
        countryHashMap.put("Falkland Islands", "Falkland Adaları");
        countryHashMap.put("The Gambia", "Gambiya");
        countryHashMap.put("Luhansk PR", "Luhansk Halk Cumhuriyeti");
        countryHashMap.put("British Virgin Islands", "Britanya Virjin Adaları");
        countryHashMap.put("Papua New Guinea", "Papua Yeni Gine");
        countryHashMap.put("South Sudan", "Güney Sudan");
        countryHashMap.put("Abkhazia", "Abhazya");
        countryHashMap.put("Artsakh", "Artsah Cumhuriyeti");
        countryHashMap.put("East Timor", "Doğu Timor");
        countryHashMap.put("Guantanamo Bay", "Guantanamo Kampı");
        countryHashMap.put("Saba", "Saba Adası");
        countryHashMap.put("Comoros", "Komorlar");
        countryHashMap.put("Tajikistan", "Tacikistan");
        countryHashMap.put("South Ossetia", "Güney Osetya");
        countryHashMap.put("Solomon Islands", "Solomon Adaları");
        countryHashMap.put("Wallis and Futuna", "Wallis ve Futuna");
        countryHashMap.put("Sahrawi Arab DR", "Sahra Dem. Arap Cum.");
        countryHashMap.put("Saint Pierre and Miquelon", "Saint Pierre ve Miquelon");
        countryHashMap.put("Marshall Islands", "Marshall Adaları");
        countryHashMap.put("American Samoa", "Amerikan Samoası");
    }
}
